apiVersion: v1
kind: Service
metadata:
  labels:
    app: couchdb
  name: couchdb-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30984
    port: 5984
    protocol: TCP
    targetPort: 5984
  selector:
    app: couchdb
  sessionAffinity: None
  type: NodePort
