---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-deployment
  labels:
    app: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: treehouses/couchdb:latest
        ports:
        - containerPort: 5984
        env:
        - name: COUCHDB_USER
          value: couchdb
        - name: COUCHDB_PASSWORD
          value: couchdb

